### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by eunikolsky** [elelay/gpodder-osx-bundle#6]
After our latest updates (#3), it'd be great to update the dependencies. `openssl` is [really old](https://github.com/elelay/gpodder-osx-bundle/blob/master/modulesets/gtk-osx-network.modules#L48).

I think we can download new modules from https://git.gnome.org/browse/gtk-osx/tree/modulesets-stable and try the build.

**Comment by elelay** [comment]
Sorry @eunikolsky but I don't have time to test now.
If you do, please test them yourself and submit a PR or I'll try when I have more time :-).

**Comment by eunikolsky** [comment]
i'll try next week. I have an error trying to download [Functional Geekery](https://www.functionalgeekery.com/) episode:
```
error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
this is due to old `openssl`.

**Comment by elelay** [comment]
Have you made progress on updating dependencies?
I'll do it this week-end.

**Comment by elelay** [comment]
and... it's building.
We'll know more tomorrow.

**Comment by eunikolsky** [comment]
hi @elelay. i've tried to update the `modulesets/` from the latest `gtk-osx` commit (surprisingly, `openssl` is still very old there). the build failed at `gobject-introspection`:
```
dyld: lazy symbol binding failed: Symbol not found: _g_cocoa_notification_backend_get_type
  Referenced from: /Users/x/proj/py/gpodder-osx-bundle/_home/jhbuild_prefix/lib/libgio-2.0.0.dylib
  Expected in: flat namespace
```

**Comment by elelay** [comment]
hi, @eunikolsky.
Didn't have the problem on 10.6, but it's ringing a bell: https://mail.gnome.org/archives/gtk-osx-users-list/2016-June/msg00001.html
Seems you wont be able to target 10.6? Let me know if changing [misc/jhbuildrc-custom#L15](https://github.com/elelay/gpodder-osx-bundle/blob/master/misc/jhbuildrc-custom#L15)
to
```` 
_target = "10.%d" % _osx_version;
setup_sdk(target=_target, sdk_version="native", architectures=[_default_arch])
````
solves it for you.

Meanwhile I've pushed updated deps. Please try from them, since it contains the updated openssl

**Comment by eunikolsky** [comment]
@elelay, thanks for the links. the patch did help. WebKit is building (with `make -j1`)…

Trying the updated version. Still can't download "Functional Geekery", and the error is different now:
```
IOError: [Errno socket error] [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)
```
weird…

> Seems you wont be able to target 10.6?

i don't know how `jhbuild` works inside, but with `clang` you can set the Base SDK version (say, `10.11` currently) and minimum deployment target (say, `10.6`) and the app should work on OSX 10.6+.

**Comment by elelay** [comment]
Yeah, I can't download episodes either.
The error is in a python stacktrace, not in webkit as I first incorrectly assumed.

I'm now thinking that the build of python still uses the systems openssl.
To confirm, can you run this command (adjusting the path to the app bundle):
```
/Applications/gPodder.app/Contents/MacOS/python
```
and then in the python interpreter
```
import ssl
ssl.OPENSSL_VERSION
```
For me it shows `'OpenSSL 0.9.8y 5 Feb 2013'`, so it's the system's libssl that gets used by python.
It seems to be set  in the setup.py script, called by the makefile.
I'll try to find a way to override it with our openssl, but not today ! Just drop me a line if/when you make progress on it, I'll do the same, so we don't waste efforts.
Cheers,

**Comment by eunikolsky** [comment]
@elelay, you're right:
```bash
$ PYTHONHOME=/Applications/gPodder.app/Contents/Resources/ /Applications/gPodder.app/Contents/MacOS/python
Python 2.7.11 (default, Jun  3 2016, 22:32:45)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> ssl.OPENSSL_VERSION
'OpenSSL 0.9.8zh 14 Jan 2016'
```
i also noticed there is no `libssl.dylib` in the app package, although it's present in `_home/jhbuild_prefix/lib`. tried copying `lib{crypto,ssl}*dylib` into `gPodder.app/Contents/Resources/lib/`, but the result is the same.

* setting `DYLD_LIBRARY_PATH` doesn't help; this may the problem:
    ```bash
$ otool -L /Applications/gPodder.app/Contents/Resources/lib/python2.7/lib-dynload/_ssl.so
/Applications/gPodder.app/Contents/Resources/lib/python2.7/lib-dynload/_ssl.so:
        /usr/lib/libssl.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
        /usr/lib/libcrypto.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 125.2.11)
```

* stumbled upon this:
    > SSLv3 has been disabled by default in httplib and its reverse dependencies due to the POODLE attack.
    
    (https://www.python.org/downloads/release/python-279/) — seems to be matching the error `SSLV3_ALERT_HANDSHAKE_FAILURE`. however, the older version should work with older protocols by default, but had a different error?!

* python from homebrew supports brewed openssl, this is somehow done via `distutils.cfg`: https://github.com/Homebrew/homebrew-core/blob/master/Formula/python.rb#L247, https://github.com/Homebrew/homebrew-core/blob/master/Formula/python.rb#L268

* these have some ideas how to build python with custom openssl (how to integrate with jhbuild?):
https://stackoverflow.com/questions/5937337/building-python-with-ssl-support-in-non-standard-location
http://stackoverflow.com/a/20740964
http://blog.irq1.com/compile-python2-python3-with-custom-openssl/

**Comment by elelay** [comment]
@eunikolsky, great !

I've considered patching `modules/Setup.dist` like said in the links you listed, but patched setup.py in the end: it already looks for openssl there so I short-circuited it and put the jhbuild path.

Now a new error:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

**Comment by elelay** [comment]
Seems like we'll have to bundle certificates (from root-ca-bundle, for instance).
Another issue is to fix the hardcoded lookup for /Volumes/MAC2/NGPO/_home/jhbuild_prefix/etc/ssl/openssl.cnf
```bash
$ sudo dtruss openssl s_client -showcerts -connect episodes.functionalgeekery.com:443 -servername episodes.functionalgeekery.com < /dev/null 2>&1 | grep _home
stat64("/Volumes/MAC2/NGPO/_home/jhbuild_prefix/lib/libssl.1.0.0.dylib\0", 0x7FFF5FBFC880, 0x7FFF5FBFCEC0)		 = 0 0
open("/Volumes/MAC2/NGPO/_home/jhbuild_prefix/lib/libssl.1.0.0.dylib\0", 0x0, 0x0)		 = 3 0
stat64("/Volumes/MAC2/NGPO/_home/jhbuild_prefix/lib/libcrypto.1.0.0.dylib\0", 0x7FFF5FBFC880, 0x7FFF5FBFCEC0)		 = 0 0
open("/Volumes/MAC2/NGPO/_home/jhbuild_prefix/lib/libcrypto.1.0.0.dylib\0", 0x0, 0x0)		 = 3 0
open_nocancel("/Volumes/MAC2/NGPO/_home/jhbuild_prefix/etc/ssl/openssl.cnf\0", 0x0, 0x1B6)		 = 3 0
stat64("/Volumes/MAC2/NGPO/_home/.rnd\0", 0x7FFF5FBFE7F0, 0x0)		 = -1 Err#2
open_nocancel("/Volumes/MAC2/NGPO/_home/jhbuild_prefix/etc/ssl/cert.pem\0", 0x0, 0x1B6)		 = -1 Err#2
stat64("/Volumes/MAC2/NGPO/_home/jhbuild_prefix/etc/ssl/certs/157753a5.0\0", 0x7FFF5FBFE700, 0x40)		 = -1 Err#2
stat64("/Volumes/MAC2/NGPO/_home/jhbuild_prefix/etc/ssl/certs/eed8c118.0\0", 0x7FFF5FBFE700, 0x40)		 = -1 Err#2
stat64("/Volumes/MAC2/NGPO/_home/jhbuild_prefix/etc/ssl/certs/6cfa716c.0\0", 0x7FFF5FBFE700, 0x40)		 = -1 Err#2
```

**Comment by elelay** [comment]
OK, so it can be forced using the environment variable CA_CERT_FILE (if we bundle a .pem, or - untested - SSL_CERT_DIR if we bundle a dir of .crt).
using this trick I can get urllib2 to open functionalgeekery
```bash
$ . env.sh
$ jhbuild shell
$ export SSL_CERT_FILE=/opt/local/etc/openssl/cert.pem 
bash-3.2$ python
Python 2.7.11 (default, Jun  9 2016, 21:33:54) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> ssl.get_default_verify_paths()
DefaultVerifyPaths(cafile='/opt/local/etc/openssl/cert.pem', capath=None, openssl_cafile_env='SSL_CERT_FILE', openssl_cafile='/Volumes/MAC2/NGPO/_home/jhbuild_prefix/etc/ssl/cert.pem', openssl_capath_env='SSL_CERT_DIR', openssl_capath='/Volumes/MAC2/NGPO/_home/jhbuild_prefix/etc/ssl/certs')
>>> import urllib2
>>> urllib2.urlopen("https://www.functionalgeekery.com/")
<addinfourl at 4315970448 whose fp = <socket._fileobject object at 0x10073e3d0>>
>>> 
```

**Comment by elelay** [comment]
I've uploaded the resulting bundle (commit 0aefdab) at  http://cloudy.elelay.fr/dropbox/gpodder-bundle-3-9-0-with-ca-0aefdab.zip
With it I'm finally able to download episodes from functional geekery. Do you confirm?

Our version of openssl is not able to use the system's KeyChain. So I'd like to bundle CAs with it. I plan to use mozilla's CAs, using the latest input file from mozilla (i.e.
http://hg.mozilla.org/mozilla-central/raw-file/FIREFOX_AURORA_47_BASE/security/nss/lib/ckfw/builtins/certdata.txt )
and a script in curl's repository to produce a working cert.pem.

Then in the readme, instructions to replacing it with one's CAs.
What do you think?

**Comment by eunikolsky** [comment]
> With it I'm finally able to download episodes from functional geekery. Do you confirm?

it works indeed! great job, @elelay.

re: CAs, it's a tricky question whom to trust, but since we have to have a list, mozilla's list should be fine. as an alternative, i've found a few commands to extract osx's certificates: https://github.com/rbenv/ruby-build/blob/master/bin/ruby-build#L965

maybe, use this link https://hg.mozilla.org/mozilla-central/raw-file/default/security/nss/lib/ckfw/builtins/certdata.txt ? — it seems to be their main branch so it should contain updates over time.

**Comment by elelay** [comment]
@eunikolsky, finally I think we are not in a position to ship updated certificates in time when a breach occurs, so I'd leave it to the system and don't ship a list.

I've followed your link to how ruby does it, and adopted its strategy (also in [homebrew openssl](https://github.com/Homebrew/homebrew-core/blob/master/Formula/openssl.rb).

See 21f1b91 where I bundle a script which updates `cert.pem` at first run and every week.
Result will appear here shortly:  http://cloudy.elelay.fr/dropbox/gpodder-bundle-3-9-0-with-ca-21f1b91.zip

**Comment by eunikolsky** [comment]
cool stuff, @elelay. I prefer this solution as well — fewer things to keep track of.

checked out the latest archive, and it works great. are you going to upload it as the official build?

there is a caveat in updating the app bundle: if it were signed, we wouldn't be able to change it w/o complains from the system. but it's fine for now.

**Comment by elelay** [comment]
So maybe create the pem in `~/Library/Application Support/org.gpodder`? I don't intend to sign the app, but it would also solve issues when gPodder.app is installed by an administrator and run by someone else: she won't be able to update the file because of file permissions.

Also, it could be better to create 
1) the pem in `~/Library/Application Support/org.gpodder.gpodder/generated.pem`
2) a symlink  `~/Library/Application Support/org.gpodder.gpodder/cert.pem` to  `generated.pem`, and reference `cert.pem` in the launcher script.

This way, people can modify the symlink to point e.g. to `/opt/local/etc/openssl/cert.pem` if they use MacPorts and update often.

What do you think? I'll upload a new release once it's settled (I guess next week).

**Comment by eunikolsky** [comment]
> So maybe create the pem in `~/Library/Application Support/org.gpodder`?

or the location of `GPODDER_HOME`? which is `~/gPodder/` in my case, and it can be `~/Library/Application Support/gpodder/` (https://github.com/gpodder/gpodder/blob/master/src/gpodder/__init__.py#L191) — although it's a dependency on the gPodder's logic.

> it would also solve issues when gPodder.app is installed by an administrator and run by someone else: she won't be able to update the file because of file permissions.

yeah, that may be a more frequent issue.

the symlinking approach seems to be more flexible indeed. i'm still not sure about the root `~/Library/Application Support/org.gpodder.gpodder/` though.

ps. pinging @thp, just in case.

**Comment by thp** [comment]
Note that we already have `~/Library/Application Support/gPodder/`, so you might want to put the files there.

**Comment by elelay** [comment]
Sorry for the delay and thanks for your input : I didn't knew about the new gPodder home on OSX.
So I emulated the same gPodder logic to not make user's `~/gPodder` ignored by creating `~/Library/Application Support/gPodder`.
64fe1d8/misc/bundle/launcher.sh seems good to go. What do you think?

**Comment by elelay** [comment]
Better use a relative path in symlink (4109433)

**Comment by thp** [comment]
>  I didn't know about the new gPodder home on OSX.

Sorry, I should have better communicated this for packagers.
It's been in since 3.7.0 actually: https://github.com/gpodder/gpodder/commit/c18b48ce7d9aff5503695bb87e934d10b1e63016

**Comment by eunikolsky** [comment]
hi @elelay and @thp. the script looks good to me, however it seems safer to add quotes around the variables where paths are stored.

**Comment by elelay** [comment]
Thanks. I've corrected the remaining instance (passes shellcheck.net).

I'll upload the 3.9.0_2 bundle containing the script now.

**Comment by eunikolsky** [comment]
@elelay, thanks for the update! i've updated the cask for homebrew: https://github.com/caskroom/homebrew-cask/pull/23247 to use the latest and greatest
